pipeline {
    agent any

    tools {
        maven 'Maven 3.9.8'
    }

    environment {
        pom = readMavenPom file: 'api-gateway/pom.xml'
        BUILD_VERSION = "${pom.version}"
        DOCKER_IMAGE = 'mohyehia99/api-gateway'
        DIR = 'api-gateway'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                script {
                    sh """ 
                        echo "Build number is: ${BUILD_VERSION}"
                    """
                    cleanWs()
                }
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'kubernetes_without_consul', url: 'https://github.com/mohyehia/spring-microservices-in-action'
            }
        }

        stage('Unit Testing') {
            steps {
                dir("${DIR}") {
                    sh 'mvn clean test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv(credentialsId: 'sonarQube-token', installationName: 'SonarQube') {
                    dir("${DIR}") {
                        sh "mvn verify sonar:sonar -DskipTests=true -Dsonar.projectKey=api-gateway -Dsonar.projectName='api-gateway'"
                    }
                }
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Trivy FS Scan') {
            steps {
                dir("${DIR}") {
                    sh 'trivy fs .'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir("${DIR}") {
                    sh "mvn spring-boot:build-image -DskipTests"
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image ${DOCKER_IMAGE}:${BUILD_VERSION}'
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'dockerHubUsername', passwordVariable: 'dockerHubPassword')]) {
                    sh "docker login -u ${env.dockerHubUsername} -p ${env.dockerHubPassword}"
                    sh "docker push ${DOCKER_IMAGE}:${BUILD_VERSION}"
                }
            }
        }

        stage('Trigger microservices-k8s-manifests Job') {
            steps {
                sh "curl -v -k --user admin:11295d15cb5acb2914d803b4d62222b728 -X POST -H 'cache-control: no-cache' -H 'Content-Type: application/x-www-form-urlencoded' --data 'DOCKER_IMAGE=${DOCKER_IMAGE}&BUILD_VERSION=${BUILD_VERSION}&APPLICATION=${DIR}' http://localhost:8080/job/microservices-k8s-manifests/buildWithParameters?token=spring-microservices-in-action-token"
            }
        }
    }
}