pipeline {
    agent any

    tools {
        maven 'Maven 3.9.8'
    }

    environment {
        pom = readMavenPom file: 'api-gateway/pom.xml'
        BUILD_VERSION = ${pom}.version
        DOCKER_IMAGE = 'mohyehia99/api-gateway'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                script {
                    cleanWs()
                }
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'kubernetes_without_consul', url: 'https://github.com/mohyehia/spring-microservices-in-action'
            }
        }

        stage('Unit Testing') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv(credentialsId: 'sonarQube-token', installationName: 'SonarQube') {
                    sh "mvn verify sonar:sonar -DskipTests=true -Dsonar.projectKey=api-gateway -Dsonar.projectName='api-gateway'"
                }
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package -Dmaven.test.skip'
            }
        }

        stage('Publish test results') {
            steps {
                junit "**/target/surefire-reports/*.xml"
            }
        }

        stage('OWASP Dependency Check') {
            steps {
                dependencyCheck additionalArguments: '''
                    -o './\'
                    -s './\'
                    -f 'ALL'
                    --prettyPrint''', odcInstallation: 'OWASP Dependency Check'
                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
            }
        }

        stage('Trivy FS Scan') {
            steps {
                sh 'trivy fs .'
            }
        }

        stage('Docker Build') {
            steps {
                sh "mvn spring-boot:build-image -DskipTests"
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image mohyehia99/api-gateway:${BUILD_VERSION}'
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'dockerHubUsername', passwordVariable: 'dockerHubPassword')]) {
                    sh "docker login -u ${env.dockerHubUsername} -p ${env.dockerHubPassword}"
                    sh "docker push mohyehia99/api-gateway:${BUILD_VERSION}"
                }
            }
        }
    }
}