version: '3.8'
services:
  consul:
    container_name: consul-ctr
    image: hashicorp/consul:latest
    restart: unless-stopped
    ports:
      - '8500:8500'
    volumes:
      - ./docker/volumes/consul/data:/consul/data
      - ./docker/volumes/consul/config/consul-config.json:/consul/config/config.json
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    extra_hosts:
      - host.docker.internal:host-gateway

  mongo-db:
    container_name: mongo-ctr
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - ./docker/volumes/mongo:/data/db