version: '3.8'
services:

  mongo-db:
    container_name: mongodb
    image: mongo:4.4.29-focal
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - ./docker/volumes/mongo/data:/data/db

  postgres-db:
    container_name: postgres-ctr
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: organization-user
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: organization-db

  redis:
    container_name: redis-ctr
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'

  redis-insight:
    container_name: redis-insight-ctr
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    ports:
      - '8001:8001'
    volumes:
      - ./docker/volumes/redis-insights:/db

  prometheus:
    container_name: prometheus-ctr
    image: prom/prometheus:v2.51.2
    restart: unless-stopped
    ports:
      - '9090:9090'
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana-ctr
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./docker/volumes/grafana/data:/var/lib/grafana
      - ./docker/volumes/grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./docker/volumes/tempo-config/tempo.yml:/etc/tempo.yml
    ports:
      - '3200:3200'   # tempo
      - '9411:9411'  # zipkin

  loki:
    image: grafana/loki:latest
    container_name: loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    ports:
      - '3100:3100'

  promtail:
    image: grafana/promtail:main
    container_name: promtail
    volumes:
      - ./docker/volumes/promtail/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    restart: unless-stopped

  api-gateway:
    image: mohyehia99/api-gateway:0.0.3
    container_name: api-gateway
    ports:
      - '8082:8082'
    depends_on:
      - tempo
      - redis
    labels:
      collect_logs: "promtail"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      ORGANIZATION_SERVICE_URI: http://organization-service:8081
      LICENSE_SERVICE_URI: http://licence-service:8083
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411/api/v2/spans

  licence-service:
    image: mohyehia99/licence-service:0.0.3
    container_name: licence-service
    ports:
      - '8083:8083'
    depends_on:
      - tempo
      - mongo-db
    labels:
      collect_logs: "promtail"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      ORGANIZATION_MS_API: http://organization-service:8081/api/v1/organizations/{organizationSlug}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411/api/v2/spans
      SPRING_APPLICATION_NAME: licence-service

  organization-service:
    image: mohyehia99/organization-service:0.0.3
    container_name: organization-service
    ports:
      - '8081:8081'
    depends_on:
      - tempo
      - postgres-db
    labels:
      collect_logs: "promtail"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411/api/v2/spans
