### find all by organization
GET http://localhost:8080/api/v1/organizations/un-org/licences

### get license by id
GET http://localhost:8080/api/v1/organizations/un-org/licences/657b16e279f9431c589ec610


### add new license
POST http://localhost:8080/api/v1/organizations/un-org/licences
Content-Type: application/json

{
  "description": "some other description",
  "productName": "dummy-license for un",
  "licenceType": "full"
}

### update license
PUT http://localhost:8080/api/v1/organizations/un-org/licences/657b167b79f9431c589ec60f
Content-Type: application/json

{
  "description": "some new license description",
  "productName": "random product name for un",
  "licenceType": "part"
}


### delete license
DELETE http://localhost:8080/api/v1/organizations/un-org/licences/657b167b79f9431c589ec60f