
### get organization by slug
GET http://localhost:8082/organization-ms/api/v1/organizations/un-org


### save new organization
POST http://localhost:8082/organization-ms/api/v1/organizations
Content-Type: application/json

{
  "name": "United Nations Organization",
  "slug": "un-org",
  "email": "un@mail.com",
  "phone": "0101110111"
}