spring:
  application:
    name: api-gateway

  data:
    redis:
      host: redis
      port: 6379
  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        format: yaml
      discovery:
        enabled: true
        register: true
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${random.uuid}
        health-check-path: /actuator/health
        metadata:
          department: ${SERVICE_DEPARTMENT:Information Technology}
          team: ${SERVICE_TEAM:Software Development}
          env: ${SERVICE_ENVIRONMENT:dev}
          region: ${SERVICE_REGION:us-east1}
    gateway:
      discovery:
        locator:
          enabled: false
      filter:
        request-rate-limiter:
          enabled: true
          deny-empty-key: false
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization-ms/**
          filters:
            - RewritePath=/organization-ms/(?<path>.*), /$\{path}
            - AddRequestHeader=X-Tenant-ID, my-org
            - AddResponseHeader=X-Tenant-ID, my-org
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
        - id: license-service
          uri: lb://license-service
          predicates:
            - Path=/license-ms/**
          filters:
            - RewritePath=/license-ms/(?<path>.*), /$\{path}
            - AddRequestHeader=X-Tenant-ID, my-org
            - AddResponseHeader=X-Tenant-ID, my-org
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

server:
  port: 8082

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace