apiVersion: v1
kind: Service
metadata:
  name: organization-service
  namespace: dev
spec:
  selector:
    app: organization-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-service-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization-service
  template:
    metadata:
      labels:
        app: organization-service
        collect_logs_with_filebeat: "true"
#      annotations:
#        co.elastic.logs/enabled: "true"
#        co.elastic.logs.json-logging/json.keys_under_root: "true"
#        co.elastic.logs.json-logging/json.add_error_key: "true"
#        co.elastic.logs.json-logging/json.message_key: "message"

    spec:
      containers:
        - name: organization-service-ctr
          image: mohyehia99/organization-service:0.0.2
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SERVER_SHUTDOWN
              value: "graceful"
          readinessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 8081
              path: /actuator/health
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 10