apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cm
  namespace: monitoring
data:
  datasources.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
        {
          "access": "proxy",
          "editable": true,
          "name": "prometheus",
          "uid": "prometheus",
          "orgId": 1,
          "type": "prometheus",
          "url": "http://prometheus:9090",
          "basicAuth": false,
          "isDefault": false,
          "jsonData": {
            "httpMethod": GET
          },
          "version": 1
        }
      ]
    }