apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
reclaimPolicy: Delete
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  clusterIP: None
  selector:
    app: mongo-db
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  serviceName: 'mongo-db'
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-ctr
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
          volumeMounts:
            - mountPath: /data/db
              name: mongo-vol
  volumeClaimTemplates:
    - metadata:
        name: mongo-vol
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: 'mongo-sc'
        resources:
          requests:
            storage: 1Gi