apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-ctr
          image: postgres:16.2
          env:
            - name: POSTGRES_USER
              value: organization-user
            - name: POSTGRES_PASSWORD
              value: P@ssw0rd
            - name: POSTGRES_DB
              value: organization-db