apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
  labels:
    name: prometheus-configuration
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'api-gateway'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['api-gateway:8082']
            labels:
              application: 'API Gateway'
              
      - job_name: 'licence-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['licence-service:8083']
            labels:
              application: 'License Service'
      
      - job_name: 'organization-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'organization-service:8083' ]
            labels:
              application: 'Organization Service'