pipeline {
    agent any

    tools {
        maven 'Maven 3.9.8'
    }

    environment {
        pom = readMavenPom file: 'organization-service/pom.xml'
        BUILD_VERSION = "${pom.version}"
        DOCKER_IMAGE = 'mohyehia99/organization-service'
        DIR = 'organization-service'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                script {
                    sh """ 
                        echo "Build number is: ${BUILD_VERSION}"
                    """
                    cleanWs()
                }
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'kubernetes_without_consul', url: 'https://github.com/mohyehia/spring-microservices-in-action'
            }
        }

        stage('Unit Testing') {
            steps {
                dir("${DIR}") {
                    sh 'mvn clean test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv(credentialsId: 'sonarQube-token', installationName: 'SonarQube') {
                    dir("${DIR}") {
                        sh "mvn verify sonar:sonar -DskipTests=true -Dsonar.projectKey=organization-service -Dsonar.projectName='organization-service'"
                    }
                }
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Package') {
            steps {
                dir("${DIR}") {
                    sh 'mvn package -Dmaven.test.skip'
                }
            }
        }

        stage('Trivy FS Scan') {
            steps {
                dir("${DIR}") {
                    sh 'trivy fs .'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir("${DIR}") {
                    sh "mvn spring-boot:build-image -DskipTests"
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image ${DOCKER_IMAGE}:${BUILD_VERSION}'
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'dockerHubUsername', passwordVariable: 'dockerHubPassword')]) {
                    sh "docker login -u ${env.dockerHubUsername} -p ${env.dockerHubPassword}"
                    sh "docker push ${DOCKER_IMAGE}:${BUILD_VERSION}"
                }
            }
        }
    }
}