global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'API Gateway'

  - job_name: 'license-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'License Service'

  - job_name: 'organization-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'Organization Service'

  - job_name: 'postgres-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9187']

  - job_name: 'mongo-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:9216' ]

  - job_name: 'elasticsearch_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:9114' ]

  - job_name: 'consul-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:9107' ]