spring:
  application:
    name: organization-service

  r2dbc:
    url: r2dbc:postgresql://postgres-db:5432/organization-db
    username: organization-user
    password: P@ssw0rd
  flyway:
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    url: jdbc:postgresql://postgres-db:5432/organization-db

server:
  port: 8081

resilience4j:
  circuit-breaker:
    instances:
      organization-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 4
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 8
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
  retry:
    instances:
      organization-service:
        max-attempts: 3
        wait-duration:
          seconds: 2
        retry-exceptions:
          - java.util.concurrent.TimeoutException

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    diskspace:
      enabled: true
    circuit-breakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      department: ${SERVICE_DEPARTMENT:Information Technology}
      team: ${SERVICE_TEAM:Software Development}
      env: ${SERVICE_ENVIRONMENT:dev}
      region: ${SERVICE_REGION:us-east1}

jaeger:
  tracing:
    url: http://jaeger:4318/v1/traces

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'