spring:
  application:
    name: organization-service

  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        format: yaml
      discovery:
        enabled: true
        register: true
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${random.uuid}
        health-check-path: /actuator/health
        metadata:
          department: ${SERVICE_DEPARTMENT:Information Technology}
          team: ${SERVICE_TEAM:Software Development}
          env: ${SERVICE_ENVIRONMENT:dev}
          region: ${SERVICE_REGION:us-east1}

server:
  port: 8081

resilience4j:
  circuit-breaker:
    instances:
      organization-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 4
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 8
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
