spring:
  application:
    name: license-service
  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        format: yaml
      discovery:
        enabled: true
        register: true
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${random.uuid}
        health-check-path: /actuator/health
        metadata:
          department: ${SERVICE_DEPARTMENT:Information Technology}
          team: ${SERVICE_TEAM:Software Development}
          env: ${SERVICE_ENVIRONMENT:dev}
          region: ${SERVICE_REGION:us-east1}

resilience4j:
  circuit-breaker:
    instances:
      license-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
      organization-service:
        failure-rate-threshold: 60
        minimum-number-of-calls: 6
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 20
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
  retry:
    instances:
      license-service:
        max-attempts: 3
        wait-duration:
          seconds: 2
        retry-exceptions:
          - java.util.concurrent.TimeoutException
      organization-service:
        max-attempts: 3
        wait-duration:
          seconds: 5
        retry-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException