spring:
  application:
    name: license-service
  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        format: yaml

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    diskspace:
      enabled: true
