spring:
  application:
    name: license-service

  data:
    mongodb:
      host: mongo-db
      port: 27017
      database: license-db

resilience4j:
  circuit-breaker:
    instances:
      license-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
      organization-service:
        failure-rate-threshold: 60
        minimum-number-of-calls: 6
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 20
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
  retry:
    instances:
      license-service:
        max-attempts: 3
        wait-duration:
          seconds: 2
        retry-exceptions:
          - java.util.concurrent.TimeoutException
      organization-service:
        max-attempts: 3
        wait-duration:
          seconds: 5
        retry-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException

server:
  port: 8083

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    diskspace:
      enabled: true
    circuit-breakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      department: ${SERVICE_DEPARTMENT:Information Technology}
      team: ${SERVICE_TEAM:Software Development}
      env: ${SERVICE_ENVIRONMENT:dev}
      region: ${SERVICE_REGION:us-east1}

jaeger:
  tracing:
    url: http://jaeger:4318/v1/traces

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


organization:
  base:
    api: ${ORGANIZATION_MS_API:http://localhost:8081/api/v1/organizations/{organizationSlug}}